export enum Types {
  SAVE_USER_LOGIN_STATE = 'SAVE_USER_LOGIN_STATE',
  SET_PAGE_LOAD_STATE = 'SET_PAGE_LOAD_STATE',
  SET_FUTURE_SCHEDULES = 'SET_FUTURE_SCHEDULES',
  SET_FILE_BUFFER = 'SET_FILE_BUFFER',
  SET_FILE_BUFFER_2 = 'SET_FILE_BUFFER_2',
  SET_MAIL_COUNT = 'SET_MAIL_COUNT',
  ALLOW_MAIL_COUNT = 'ALLOW_MAIL_COUNT',
  SET_ITEM_TO_WORKSPACE = 'SET_ITEM_TO_WORKSPACE',
  CLEAR_WORKSPACE = 'CLEAR_WORKSPACE',
}